services:
  mysql:
    image: mysql:8.0
    container_name: ${SOAP_DB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${SOAP_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SOAP_DB_NAME}
      MYSQL_USER: ${SOAP_DB_USER}
      MYSQL_PASSWORD: ${SOAP_DB_USER_PASSWORD}


    ports:
      - "${SOAP_DB_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql
  
  soapapi:
    build: .
    container_name: ${SOAP_API_CONTAINER_NAME}

    depends_on:
      - mysql

    ports:
      - "${SOAP_API_PORT}:8080"

    env_file:
      - .env

volumes:
  mysql_data: